[package]
name = "test_sandbox"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
transformers = { path = "../transformers", version = "0.0.13", features = ["cuda"] }
